### PR TITLE
refactor: remove Discord Provider 

### LINKED ISSUE #8: Remove Discord Provider
Remove the Discord Provider and related enviornment variables from Next-Auth.

### PR DESCRIPTION
**Pull request by ranaprerna**
closes #8

### CODE REVIEW

**Review by davidtaing — CHANGES_REQUESTED** [review]
Hi @ranaprerna,
The code looks good to me. Well done and thank you for helping me out.

**For the first commit:**
I think using `refactor` instead of `feat` for the commit makes more sense because we're not adding anything to the codebase.

Can you please rename the commit message title to `refactor: remove Discord Provider`?

**Review by davidtaing — CHANGES_REQUESTED** [review]
**Second commit**
Can you please rename the commit message to "refactor: remove Discord env vars"?

I like to use `git rebase main -i` and use that to rename the commits. After the changes are done, I would force push with `git push origin --force`.

It's fine for now, but keep in mind that you shouldn't force push into the main branch as it will override the history. <-- Don't worry about this for now, just keep it in mind for next time.

Overall, I think force pushing is great tool, especially when you are improving clarity.

**Comment by davidtaing** [comment]
All done @ranaprerna. Thank you!

**Comment by ranaprerna** [comment]
Thank you, David!!

**Pull request merged**
